# Numpy Tutorial

In [53]:
import numpy as np
from IPython.display import display


# creating vector and matrix

In [54]:
# create a vector
a = np.array([1, 2, 3], dtype='int8')
a

array([1, 2, 3], dtype=int8)

In [55]:
# check dimension of the array
a.shape

(3,)

In [56]:
# create a matrix (>=2 dimension)
b = np.array([[1,2,3],[4,5,6]], dtype='float64')
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [57]:
# check dimension of the array
b.shape

(2, 3)

# Indexing

In [58]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
display(a[0]); display(a[-1])

array([1, 2, 3])

array([7, 8, 9])

In [60]:
display(a[1,1]); display(a[-1,-1])

5

9

In [61]:
display(a[1:,:]); display(a[:,:1])

array([[4, 5, 6],
       [7, 8, 9]])

array([[1],
       [4],
       [7]])

In [62]:
# choose 1st and -1st rows
# choose 1st and -1st columns
display(a[[1,-1],:]); display(a[:,[1,-1]])

array([[4, 5, 6],
       [7, 8, 9]])

array([[2, 3],
       [5, 6],
       [8, 9]])

# Element wise opeation

In [63]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [64]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [65]:
display(a+b); display(a-b); display(a*b); display(a/b)

array([[ 6,  8],
       [10, 12]])

array([[-4, -4],
       [-4, -4]])

array([[ 5, 12],
       [21, 32]])

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [66]:
a+5

array([[6, 7],
       [8, 9]])

In [67]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]); b = np.array([[1,2,3]])
display(a); display(b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3]])

In [68]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [69]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]); b = np.array([[1],[2],[3]])
display(a); display(b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1],
       [2],
       [3]])

In [70]:
a+b

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

# Matrix Operation

In [71]:
# A is a matrix that have 3x2 dimensions
A = np.array([[1,2],
              [3,4],
              [5,6]])
# B is a matrix that have 2x1 dimensions
B = np.array([[1],
             [5]])
display(A); display(B)

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[1],
       [5]])

In [72]:
# the result matrix has 3x1 dimensions
np.dot(A,B)

array([[11],
       [23],
       [35]])

In [73]:
# Transpose matrix
a = np.array([[1,3,2],
             [4,9,6],
             [7,1,3]])
display(a)

array([[1, 3, 2],
       [4, 9, 6],
       [7, 1, 3]])

In [74]:
display(a.T)

array([[1, 4, 7],
       [3, 9, 1],
       [2, 6, 3]])

In [75]:
# Find determinant of matrix
display(np.linalg.det(a))

-6.999999999999995

In [76]:
# Find inverse of matrix
display(np.linalg.inv(a))

array([[-3.00000000e+00,  1.00000000e+00, -1.98254112e-16],
       [-4.28571429e+00,  1.57142857e+00, -2.85714286e-01],
       [ 8.42857143e+00, -2.85714286e+00,  4.28571429e-01]])

# Find Statistical values

In [77]:
a = np.array([[1,3],
             [4,9],
             [7,1]])
display(a)

array([[1, 3],
       [4, 9],
       [7, 1]])

In [78]:
# Find min,max,mean,standard deviation
print('min:{}\tmax:{}\tmean:{}\tstd:{}'.format(np.min(a),np.max(a),np.mean(a),np.std(a)))

min:1	max:9	mean:4.166666666666667	std:2.9674156357941426


In [79]:
# Find min,max,mean,standard deviation each row
print('min:{}\tmax:{}\tmean:{}\tstd:{}'.format(np.min(a,axis=1),np.max(a,axis=1),np.mean(a,axis=1),np.std(a,axis=1)))

min:[1 4 1]	max:[3 9 7]	mean:[2.  6.5 4. ]	std:[1.  2.5 3. ]


In [80]:
# Find min,max,mean,standard deviation each column
print('min:{}\tmax:{}\tmean:{}\tstd:{}'.format(np.min(a,axis=0),np.max(a,axis=0),np.mean(a,axis=0),np.std(a,axis=0)))

min:[1 1]	max:[7 9]	mean:[4.         4.33333333]	std:[2.44948974 3.39934634]


# Reshape

In [81]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
display(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
display(a.reshape(9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [86]:
# (1,-1) means that any column but only one row
display(a.reshape(1,-1))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Random

In [87]:
# set up seed for random to original value
np.random.seed(1)

In [88]:
# create an array to random values from 0 to 1 (0,1)
display(np.random.rand(3,2))

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02]])

In [89]:
# create an array to random in terms of normal distribution (mean=0, std=1)
display(np.random.randn(3,2))

array([[-0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ],
       [ 1.74481176, -0.7612069 ]])

In [93]:
# random values refered from the list and can set up each probability
display(np.random.choice([3,'nay',7,'yay',11],p=[0.1,0.1,0.2,0.3,0.3]))


'yay'