In [4]:
import numpy as np

In [5]:
x = np.random(, shape=(3,8))



SyntaxError: invalid syntax (<ipython-input-5-9d198eed46f5>, line 1)

In [6]:
-5.08521926e-01 / -0.1048553

4.849749378429131

In [7]:
1.74333019e-01 / -0.14200179

-1.227681841193692

# >>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.divide(x1, x2)
array([[ NaN,  1. ,  1. ],
       [ Inf,  4. ,  2.5],
       [ Inf,  7. ,  4. ]])

In [8]:
x1 = np.arange(9.0).reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [13]:
x2 = np.arange(3.0).reshape(3, 1)
x2

array([[0.],
       [1.],
       [2.]])

In [14]:
x1/x2

C:\Users\2TwO2\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\2TwO2\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, inf, inf],
       [3. , 4. , 5. ],
       [3. , 3.5, 4. ]])